name: Build, Test & Deploy

on: 
  push:
    branches:
      - master
      - impl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.6
      - name: Build Linux x64
        run: GOOS=linux GOARCH=amd64 go build ./cmd/docker-compose-watcher
      - name: Build Linux ARM
        run: GOOS=linux GOARCH=arm go build ./cmd/docker-compose-watcher
      - name: Build Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build ./cmd/docker-compose-watcher
      - name: Build Windows x86
        run: GOOS=linux GOARCH=arm go build ./cmd/docker-compose-watcher
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.6
      - name: Test
        run: go test ./...
  #release:
  #  runs-on: ubuntu-latest
  #  needs: [build, test]
  #  steps: